/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.restaurant.views.movements;

import com.restaurant.classes.InOutProduct;
import com.restaurant.classes.InOutProductDetail;
import com.restaurant.classes.Product;
import com.restaurant.tablemodels.TableModelsInOutProducts;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author Luis
 */
public class MainInOutProduct extends javax.swing.JInternalFrame {

    /**
     * Creates new form MainInOutProduct
     */
    
    InOutProduct IOP = new InOutProduct();
    
    Product product = new Product();
    InOutProductDetail IOPD = new InOutProductDetail();
    TableModelsInOutProducts TMIOP = new TableModelsInOutProducts();
    Date date = new Date();
    public MainInOutProduct() {
        initComponents();
        this.IOP.readFile();
        this.IOPD.readFile();
        this.product.readFile();
        this.TMIOP.initTable(jt_Info);
        this.jd_date.setDate(date);
        
        jd_date.setDateFormatString("dd/MM/yyyy");
        
    }
    
    
    
    public void clear(){
        this.txt_idInOut.setText("");
        this.txt_idProduct.setText("");
        this.txt_price.setText("");
        this.txt_maxQuantity.setText("");
        this.txt_QuantityProduct.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        Header = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_idInOut = new javax.swing.JTextField();
        jr_in = new javax.swing.JRadioButton();
        jr_out = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jd_date = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        txt_idProduct = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_QuantityProduct = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_maxQuantity = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txt_price = new javax.swing.JTextField();
        btn_addDetail = new javax.swing.JButton();
        Body = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jt_Info = new javax.swing.JTable();
        Actions = new javax.swing.JPanel();
        Btn_Add = new javax.swing.JButton();
        btn_Modify = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jLabel1.setText("Id Entrada-Salida");

        txt_idInOut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_idInOutMouseClicked(evt);
            }
        });
        txt_idInOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_idInOutActionPerformed(evt);
            }
        });
        txt_idInOut.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_idInOutKeyReleased(evt);
            }
        });

        buttonGroup1.add(jr_in);
        jr_in.setSelected(true);
        jr_in.setText("Entrada");

        buttonGroup1.add(jr_out);
        jr_out.setText("Salida");

        jLabel2.setText("Tipo");

        jLabel3.setText("Fecha");

        jLabel4.setText("Id Producto");

        txt_idProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_idProductActionPerformed(evt);
            }
        });
        txt_idProduct.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_idProductKeyReleased(evt);
            }
        });

        jLabel5.setText("Cantidad");

        jLabel6.setText("Existencia");

        txt_maxQuantity.setEditable(false);

        jLabel7.setText("Precio");

        txt_price.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_priceActionPerformed(evt);
            }
        });

        btn_addDetail.setText("Agregar Producto");
        btn_addDetail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addDetailActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout HeaderLayout = new javax.swing.GroupLayout(Header);
        Header.setLayout(HeaderLayout);
        HeaderLayout.setHorizontalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(HeaderLayout.createSequentialGroup()
                        .addGroup(HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                        .addGroup(HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_QuantityProduct, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_price, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(HeaderLayout.createSequentialGroup()
                        .addGroup(HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_idProduct, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                            .addComponent(txt_idInOut))))
                .addGroup(HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(HeaderLayout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addComponent(jLabel3)
                        .addGap(32, 32, 32)
                        .addComponent(jd_date, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                        .addComponent(jLabel2))
                    .addGroup(HeaderLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_maxQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_addDetail)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jr_in)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jr_out)
                .addGap(72, 72, 72))
        );
        HeaderLayout.setVerticalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jd_date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(txt_idInOut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jr_in)
                        .addComponent(jr_out)
                        .addComponent(jLabel2)
                        .addComponent(jLabel3)))
                .addGap(18, 18, 18)
                .addGroup(HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txt_idProduct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txt_QuantityProduct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(txt_maxQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_addDetail))
                .addGap(7, 7, 7)
                .addGroup(HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txt_price, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jt_Info.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jt_Info);

        javax.swing.GroupLayout BodyLayout = new javax.swing.GroupLayout(Body);
        Body.setLayout(BodyLayout);
        BodyLayout.setHorizontalGroup(
            BodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 711, Short.MAX_VALUE)
        );
        BodyLayout.setVerticalGroup(
            BodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
        );

        Actions.setLayout(new java.awt.GridLayout(1, 0));

        Btn_Add.setText("Agregar");
        Btn_Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_AddActionPerformed(evt);
            }
        });
        Actions.add(Btn_Add);

        btn_Modify.setText("Modificar");
        btn_Modify.setEnabled(false);
        btn_Modify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ModifyActionPerformed(evt);
            }
        });
        Actions.add(btn_Modify);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Actions, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Body, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Actions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Body, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_idInOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_idInOutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_idInOutActionPerformed

    private void txt_idInOutKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_idInOutKeyReleased
        try {
            this.TMIOP.initTable(jt_Info);
            if (this.txt_idInOut.getText().isEmpty())
                return;
            
            this.Btn_Add.setEnabled(true);
            this.btn_Modify.setEnabled(false);
            int idIntOut = Integer.parseInt(this.txt_idInOut.getText());
            boolean found = false;
            
            for (InOutProduct object : this.IOP.getInOutProducts()) {
                if (object.getIdInOut() == idIntOut){
                    found = true; 
                    this.TMIOP.getInOutActive(jt_Info, this.IOPD.getInOutProductDetails(), idIntOut);
                    this.Btn_Add.setEnabled(false);
                    this.btn_Modify.setEnabled(true);
                    this.jd_date.setDate(object.getDateReg());
                    if (object.getKindInOut() == 1) {
                        this.jr_in.setSelected(true);
                    }else{
                        this.jr_out.setSelected(true);
                    }
                    break;
                }   
            }
            if (!found) {
                this.Btn_Add.setEnabled(true);
                this.btn_Modify.setEnabled(false);
            }
            
            if (found) {
                this.TMIOP.getInOutActive(jt_Info, this.IOPD.getInOutProductDetails(), idIntOut);
                
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, e, "Opss..", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_txt_idInOutKeyReleased

    private void txt_idProductKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_idProductKeyReleased
        try {
            int idProduct = Integer.parseInt(this.txt_idProduct.getText());
            
            boolean found = false;
            
            for (Product product1 : this.product.getProducts()) {
                
                if (idProduct == product1.getIdProduct()) {
                    this.txt_maxQuantity.setText(String.valueOf(product1.getStock()));
                    this.txt_price.setText(String.valueOf(product1.getPrice()));
                    found= true;
                    break;
                }
            }
            if (!found) {
                JOptionPane.showMessageDialog(this, "Este producto no existe", "Opss..", JOptionPane.ERROR_MESSAGE);
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, e, "Opss..", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_txt_idProductKeyReleased

    private void Btn_AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_AddActionPerformed

        try {
            int idProduct = Integer.parseInt(this.txt_idProduct.getText());
            int idIntOut = Integer.parseInt(this.txt_idInOut.getText());
            this.txt_idInOut.setEnabled(true);
            this.IOP.add(idIntOut, idIntOut, this.jd_date.getDate());
            JOptionPane.showMessageDialog(this, "Agregando", "Nice", JOptionPane.ERROR_MESSAGE);
            clear();
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, e, "Opss..", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_Btn_AddActionPerformed

    private void btn_addDetailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addDetailActionPerformed
        
        try {
            this.txt_idInOut.setEnabled(false);
            if (this.txt_idInOut.getText().isEmpty() || this.txt_idProduct.getText().isEmpty() || this.txt_price.getText().isEmpty() || this.txt_QuantityProduct.getText().isEmpty()) {
               JOptionPane.showMessageDialog(this, "Error Campos Vacios", "Opss..", JOptionPane.ERROR_MESSAGE);
                return;
            }
            boolean found = false;
            
            int idIntOut = Integer.parseInt(this.txt_idInOut.getText());
            int idProduct =  Integer.parseInt(this.txt_idProduct.getText());
            double Quantity = Double.parseDouble(this.txt_QuantityProduct.getText());
            double Price = Double.parseDouble(this.txt_price.getText());
            this.txt_idInOut.setEnabled(false);
            
            for (InOutProductDetail inOutProductDetail : this.IOPD.getInOutProductDetails()) {
                if (inOutProductDetail.getInOutProductDetail() == idIntOut && inOutProductDetail.getIdProduct() == idProduct) {
                    inOutProductDetail.setQuantity(Quantity);
                    inOutProductDetail.setPrice(Price);
 
                    found = true;
                    
                }
                
            }
            if (!found) {
                this.IOPD.add(idIntOut, 0, idProduct, Quantity, Price);
                
            }
            
           
            
            this.TMIOP.getInOutActive(jt_Info, this.IOPD.getInOutProductDetails(), idIntOut);
        } catch (NumberFormatException e) {
             JOptionPane.showMessageDialog(this, e, "Opss..", JOptionPane.ERROR_MESSAGE);
        } 
    }//GEN-LAST:event_btn_addDetailActionPerformed

    private void txt_idInOutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_idInOutMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_idInOutMouseClicked

    private void txt_priceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_priceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_priceActionPerformed

    private void txt_idProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_idProductActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_idProductActionPerformed

    private void btn_ModifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ModifyActionPerformed
       
        try {
            int idIntOut = Integer.parseInt(this.txt_idInOut.getText());
           
            this.IOP.modify(idIntOut, this.jr_in.isSelected() ? 1 : 2  , this.jd_date.getDate());
            JOptionPane.showMessageDialog(this, "Modificando", "Nice", JOptionPane.INFORMATION_MESSAGE);
            clear();
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, e, "Opss..", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btn_ModifyActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Actions;
    private javax.swing.JPanel Body;
    private javax.swing.JButton Btn_Add;
    private javax.swing.JPanel Header;
    private javax.swing.JButton btn_Modify;
    private javax.swing.JButton btn_addDetail;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private com.toedter.calendar.JDateChooser jd_date;
    private javax.swing.JRadioButton jr_in;
    private javax.swing.JRadioButton jr_out;
    private javax.swing.JTable jt_Info;
    private javax.swing.JTextField txt_QuantityProduct;
    private javax.swing.JTextField txt_idInOut;
    private javax.swing.JTextField txt_idProduct;
    private javax.swing.JTextField txt_maxQuantity;
    private javax.swing.JTextField txt_price;
    // End of variables declaration//GEN-END:variables
}
